In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pickle as pkl

sns.set_style("darkgrid")

In [2]:
results_df = {"best_epoch": [], "best_step": [], "best_val_loss": [], "input_relative_coords": [], "output_relative_coords": [], "decoder_type": [], "test_l2_point": [], "test_l2_instance": [], "seed": []}

for filename in os.listdir(f"../../sketch_representations/checkpoints/experiment2/"):
    if not os.path.exists(f"../../sketch_representations/results/experiment2/{filename}.pkl"):
        continue

    checkpoint_df = pd.read_csv(f"../../sketch_representations/checkpoints/experiment2/{filename}/lightning_logs/version_0/metrics.csv")
    metrics = checkpoint_df.iloc[checkpoint_df['val_loss'].idxmin()]
    results_df["best_epoch"].append(metrics['epoch'].astype(int))
    results_df["best_step"].append(metrics['step'].astype(int))
    results_df["best_val_loss"].append(metrics['val_loss'])

    with open(f"../../sketch_representations/results/experiment2/{filename}.pkl", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys():
            if key in ["run", "best_epoch", "best_step", "best_val_loss"]: continue
            results_df[key].append(results["test_results"][key] if key in ["test_l2_point", "test_l2_instance"] else results["args"][key])

results_df = pd.DataFrame(results_df)
results_df.groupby(["decoder_type", "input_relative_coords", "output_relative_coords"])[['test_l2_point', 'test_l2_instance', 'best_epoch', 'best_step', 'best_val_loss']].agg(['mean', 'sem'])

                                                          test_l2_point  \
                                                                   mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                       0.025959
                                   True                        0.298583
             True                  False                       0.194770
                                   True                        0.418907
ffn          False                 False                       0.002967
                                   True                        0.048211
             True                  False                       0.004711
                                   True                        0.086883
nar          False                 False                       0.003065
                                   True                        0.028746
             True                  False                       0.004524
                                   True                        0.044600
nar-enc      False                 False                       0.002333
                                   True                        0.027373
             True                  False                       0.003757
                                   True                        0.041822

                                                                     \
                                                                sem
decoder_type input_relative_coords output_relative_coords
ar           False                 False                        NaN
                                   True                         NaN
             True                  False                        NaN
                                   True                    0.021894
ffn          False                 False                   0.000065
                                   True                    0.001552
             True                  False                   0.000103
                                   True                    0.006097
nar          False                 False                   0.000104
                                   True                    0.001030
             True                  False                   0.000068
                                   True                    0.008886
nar-enc      False                 False                   0.000048
                                   True                    0.004981
             True                  False                   0.000047
                                   True                    0.004193

                                                          test_l2_instance  \
                                                                      mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                          0.024279
                                   True                           0.269727
             True                  False                          0.196253
                                   True                           0.392795
ffn          False                 False                          0.002141
                                   True                           0.028407
             True                  False                          0.003810
                                   True                           0.053660
nar          False                 False                          0.002119
                                   True                           0.017977
             True                  False                          0.003420
                                   True                           0.028720
nar-enc      False                 False                          0.001753
                                   True                           0.016440
             True                  False                          0.003004
                                   True                           0.026337

                                                                     \
                                                                sem
decoder_type input_relative_coords output_relative_coords
ar           False                 False                        NaN
                                   True                         NaN
             True                  False                        NaN
                                   True                    0.021357
ffn          False                 False                   0.000048
                                   True                    0.001060
             True                  False                   0.000115
                                   True                    0.004242
nar          False                 False                   0.000066
                                   True                    0.001020
             True                  False                   0.000082
                                   True                    0.006556
nar-enc      False                 False                   0.000040
                                   True                    0.003131
             True                  False                   0.000057
                                   True                    0.003048

                                                          best_epoch  \
                                                                mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                   15.000000
                                   True                    14.000000
             True                  False                    6.000000
                                   True                    12.000000
ffn          False                 False                   15.000000
                                   True                    14.666667
             True                  False                   15.000000
                                   True                    13.000000
nar          False                 False                   15.000000
                                   True                    15.000000
             True                  False                   15.000000
                                   True                    14.000000
nar-enc      False                 False                   15.000000
                                   True                    15.000000
             True                  False                   14.666667
                                   True                    14.333333

                                                                    best_step  \
                                                                sem      mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                        NaN   73499.0
                                   True                         NaN   67499.0
             True                  False                        NaN   31499.0
                                   True                    1.000000   58499.0
ffn          False                 False                   0.000000   73999.0
                                   True                    0.333333   71999.0
             True                  False                   0.000000   74999.0
                                   True                    1.527525   62499.0
nar          False                 False                   0.000000   74499.0
                                   True                    0.000000   73999.0
             True                  False                   0.000000   72999.0
                                   True                    0.577350   68999.0
nar-enc      False                 False                   0.000000   74499.0
                                   True                    0.000000   72999.0
             True                  False                   0.333333   72999.0
                                   True                    0.333333   70499.0

                                                                        \
                                                                   sem
decoder_type input_relative_coords output_relative_coords
ar           False                 False                           NaN
                                   True                            NaN
             True                  False                           NaN
                                   True                    3000.000000
ffn          False                 False                    500.000000
                                   True                    1500.000000
             True                  False                      0.000000
                                   True                    7566.372975
nar          False                 False                    500.000000
                                   True                     500.000000
             True                  False                    500.000000
                                   True                    3122.498999
nar-enc      False                 False                    500.000000
                                   True                    1000.000000
             True                  False                   1322.875656
                                   True                    2598.076211

                                                          best_val_loss  \
                                                                   mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                       0.025970
                                   True                        0.016466
             True                  False                       0.194637
                                   True                        0.020533
ffn          False                 False                       0.002958
                                   True                        0.004913
             True                  False                       0.004697
                                   True                        0.004529
nar          False                 False                       0.003060
                                   True                        0.004040
             True                  False                       0.004516
                                   True                        0.003281
nar-enc      False                 False                       0.002326
                                   True                        0.003672
             True                  False                       0.003740
                                   True                        0.003388


                                                                sem
decoder_type input_relative_coords output_relative_coords
ar           False                 False                        NaN
                                   True                         NaN
             True                  False                        NaN
                                   True                    0.001525
ffn          False                 False                   0.000065
                                   True                    0.000089
             True                  False                   0.000102
                                   True                    0.000252
nar          False                 False                   0.000104
                                   True                    0.000071
             True                  False                   0.000067
                                   True                    0.000153
nar-enc      False                 False                   0.000048
                                   True                    0.000032
             True                  False                   0.000048
                                   True                    0.000043

In [7]:
results_df = {"best_epoch": [], "best_step": [], "best_val_loss": [], "relative_coords": [], "pen_state": [], "stroke_embedding": [], "sketch_pos": [], "stroke_pos": [], "test_p_metric": [], "test_c_metric": [], "seed": []}

for filename in os.listdir(f"../checkpoints/experiment3/"):
    if not os.path.exists(f"../results/experiment3/{filename}.pkl"):
        continue

    checkpoint_df = pd.read_csv(f"../checkpoints/experiment3/{filename}/lightning_logs/version_0/metrics.csv")
    metrics = checkpoint_df.iloc[checkpoint_df['val_loss'].idxmin()]
    results_df["best_epoch"].append(metrics['epoch'].astype(int))
    results_df["best_step"].append(metrics['step'].astype(int))
    results_df["best_val_loss"].append(metrics['val_loss'])

    with open(f"../results/experiment3/{filename}.pkl", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys() - {"dataset"}:
            if key in ["run", "best_epoch", "best_step", "best_val_loss"]: continue
            results_df[key].append(results["test_results"][key] if key in ["test_p_metric", "test_c_metric"] else results["args"][key])

results_df = pd.DataFrame(results_df)
results_df.groupby(["relative_coords", "pen_state", "stroke_embedding", "sketch_pos", "stroke_pos"])[['test_p_metric', 'test_c_metric', 'best_epoch', 'best_step', 'best_val_loss']].agg(['mean', 'sem'])

                                                                 test_p_metric  \
                                                                          mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False           0.645324
                                                      True            0.784479
                                           True       False           0.804277
                          True             False      False           0.870260
                                                      True            0.864809
                                           True       False           0.846125
                True      False            False      False           0.681690
                                                      True            0.827053
                                           True       False           0.871909
True            False     False            False      False           0.186086
                                                      True            0.406015
                                           True       False           0.406850
                          True             False      False           0.477246
                                                      True            0.538357
                                           True       False           0.491954
                True      False            False      False           0.217829
                                                      True            0.417183
                                           True       False           0.480536

                                                                            \
                                                                       sem
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False       0.003406
                                                      True        0.010461
                                           True       False       0.012286
                          True             False      False       0.006390
                                                      True        0.007838
                                           True       False       0.005811
                True      False            False      False       0.006723
                                                      True        0.002111
                                           True       False       0.005317
True            False     False            False      False       0.001881
                                                      True        0.022592
                                           True       False       0.003216
                          True             False      False       0.011734
                                                      True        0.002407
                                           True       False       0.006212
                True      False            False      False       0.004928
                                                      True        0.009572
                                           True       False       0.005523

                                                                 test_c_metric  \
                                                                          mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False           0.468522
                                                      True            0.688138
                                           True       False           0.707582
                          True             False      False           0.812322
                                                      True            0.803329
                                           True       False           0.777950
                True      False            False      False           0.506983
                                                      True            0.744759
                                           True       False           0.802003
True            False     False            False      False           0.116722
                                                      True            0.286832
                                           True       False           0.313922
                          True             False      False           0.434118
                                                      True            0.481772
                                           True       False           0.438871
                True      False            False      False           0.129844
                                                      True            0.296851
                                           True       False           0.401667

                                                                            \
                                                                       sem
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False       0.004734
                                                      True        0.011779
                                           True       False       0.014618
                          True             False      False       0.008716
                                                      True        0.010635
                                           True       False       0.008088
                True      False            False      False       0.009154
                                                      True        0.002108
                                           True       False       0.007927
True            False     False            False      False       0.003817
                                                      True        0.011403
                                           True       False       0.004140
                          True             False      False       0.012073
                                                      True        0.003108
                                           True       False       0.007009
                True      False            False      False       0.001393
                                                      True        0.005523
                                           True       False       0.004363

                                                                 best_epoch  \
                                                                       mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False            19.8
                                                      True             34.0
                                           True       False            24.4
                          True             False      False            27.2
                                                      True             18.6
                                           True       False            16.4
                True      False            False      False            18.2
                                                      True             45.6
                                           True       False            41.8
True            False     False            False      False             7.4
                                                      True             25.2
                                           True       False            17.2
                          True             False      False            20.0
                                                      True             20.6
                                           True       False            21.6
                True      False            False      False            20.2
                                                      True             26.0
                                           True       False            20.6

                                                                            \
                                                                       sem
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False       1.200000
                                                      True        7.204165
                                           True       False       5.836095
                          True             False      False       4.758151
                                                      True        3.043025
                                           True       False       1.166190
                True      False            False      False       1.714643
                                                      True        3.867816
                                           True       False       2.200000
True            False     False            False      False       0.509902
                                                      True        1.462874
                                           True       False       0.583095
                          True             False      False       0.836660
                                                      True        1.166190
                                           True       False       0.678233
                True      False            False      False       3.624914
                                                      True        1.000000
                                           True       False       1.913113

                                                                 best_step  \
                                                                      mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False         1330.2
                                                      True          2239.0
                                           True       False         1624.6
                          True             False      False         1803.8
                                                      True          1253.4
                                           True       False         1112.6
                True      False            False      False         1227.8
                                                      True          2981.4
                                           True       False         2738.2
True            False     False            False      False          536.6
                                                      True          1675.8
                                           True       False         1163.8
                          True             False      False         1343.0
                                                      True          1381.4
                                           True       False         1445.4
                True      False            False      False         1355.8
                                                      True          1727.0
                                           True       False         1381.4

                                                                              \
                                                                         sem
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False        76.800000
                                                      True        461.066590
                                           True       False       373.510053
                          True             False      False       304.521658
                                                      True        194.753588
                                           True       False        74.636184
                True      False            False      False       109.737140
                                                      True        247.540219
                                           True       False       140.800000
True            False     False            False      False        32.633725
                                                      True         93.623929
                                           True       False        37.318092
                          True             False      False        53.546242
                                                      True         74.636184
                                           True       False        43.406912
                True      False            False      False       231.994483
                                                      True         64.000000
                                           True       False       122.439209

                                                                 best_val_loss  \
                                                                          mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False           1.218124
                                                      True            0.776473
                                           True       False           0.743838
                          True             False      False           0.541744
                                                      True            0.525952
                                           True       False           0.597320
                True      False            False      False           1.018923
                                                      True            0.650714
                                           True       False           0.557511
True            False     False            False      False           3.288916
                                                      True            2.170671
                                           True       False           2.380488
                          True             False      False           2.063567
                                                      True            1.858011
                                           True       False           2.015366
                True      False            False      False           3.076177
                                                      True            2.137204
                                           True       False           2.012444


                                                                       sem
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False       0.027525
                                                      True        0.025446
                                           True       False       0.033636
                          True             False      False       0.017205
                                                      True        0.019977
                                           True       False       0.014628
                True      False            False      False       0.010874
                                                      True        0.021497
                                           True       False       0.020379
True            False     False            False      False       0.011302
                                                      True        0.096079
                                           True       False       0.015800
                          True             False      False       0.069168
                                                      True        0.024222
                                           True       False       0.023810
                True      False            False      False       0.029889
                                                      True        0.056317
                                           True       False       0.013565