In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pickle as pkl

sns.set_style("darkgrid")

In [7]:
results_df = {"best_epoch": [], "best_step": [], "best_val_loss": [], "input_relative_coords": [], "output_relative_coords": [], "decoder_type": [], "test_l2_point": [], "test_l2_instance": [], "seed": []}

for filename in os.listdir(f"../checkpoints/experiment2/"):
    if not os.path.exists(f"../results/experiment2/{filename}.pkl"):
        continue

    checkpoint_df = pd.read_csv(f"../checkpoints/experiment2/{filename}/lightning_logs/version_0/metrics.csv")
    metrics = checkpoint_df.iloc[checkpoint_df['val_loss'].idxmin()]
    results_df["best_epoch"].append(metrics['epoch'].astype(int))
    results_df["best_step"].append(metrics['step'].astype(int))
    results_df["best_val_loss"].append(metrics['val_loss'])

    with open(f"../results/experiment2/{filename}.pkl", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys():
            if key in ["run", "best_epoch", "best_step", "best_val_loss"]: continue
            results_df[key].append(results["test_results"][key] if key in ["test_l2_point", "test_l2_instance"] else results["args"][key])

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["decoder_type", "input_relative_coords", "output_relative_coords"])[['test_l2_point', 'test_l2_instance', 'best_epoch', 'best_step', 'best_val_loss']].agg(['mean', 'std'])
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')] * 100
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')].round(3).map(lambda x: f"{x:06.3f}")
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')] * 100
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')].round(3).map(lambda x: f"{x:06.3f}")
results_df

                                                          test_l2_point  \
                                                                   mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                         25.523
                                   True                          81.222
             True                  False                         51.465
                                   True                          63.359
ar-enc       False                 False                         21.146
                                   True                          75.842
             True                  False                         40.762
                                   True                          58.503
ffn          False                 False                         00.297
                                   True                          04.821
             True                  False                         00.471
                                   True                          08.688
nar          False                 False                         00.306
                                   True                          02.875
             True                  False                         00.452
                                   True                          04.460
nar-enc      False                 False                         00.233
                                   True                          02.737
             True                  False                         00.376
                                   True                          04.182

                                                                   \
                                                              std
decoder_type input_relative_coords output_relative_coords
ar           False                 False                   02.941
                                   True                    10.396
             True                  False                   06.991
                                   True                    05.546
ar-enc       False                 False                   01.337
                                   True                    04.528
             True                  False                   03.956
                                   True                    05.394
ffn          False                 False                   00.011
                                   True                    00.269
             True                  False                   00.018
                                   True                    01.056
nar          False                 False                   00.018
                                   True                    00.178
             True                  False                   00.012
                                   True                    01.539
nar-enc      False                 False                   00.008
                                   True                    00.863
             True                  False                   00.008
                                   True                    00.726

                                                          test_l2_instance  \
                                                                      mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                          0.239805
                                   True                           0.837175
             True                  False                          0.483750
                                   True                           0.639928
ar-enc       False                 False                          0.210303
                                   True                           0.793817
             True                  False                          0.380180
                                   True                           0.604421
ffn          False                 False                          0.002141
                                   True                           0.028407
             True                  False                          0.003810
                                   True                           0.053660
nar          False                 False                          0.002119
                                   True                           0.017977
             True                  False                          0.003420
                                   True                           0.028720
nar-enc      False                 False                          0.001753
                                   True                           0.016440
             True                  False                          0.003004
                                   True                           0.026337

                                                                     \
                                                                std
decoder_type input_relative_coords output_relative_coords
ar           False                 False                   0.020892
                                   True                    0.121134
             True                  False                   0.078798
                                   True                    0.046387
ar-enc       False                 False                   0.008545
                                   True                    0.052079
             True                  False                   0.043134
                                   True                    0.050608
ffn          False                 False                   0.000084
                                   True                    0.001836
             True                  False                   0.000200
                                   True                    0.007348
nar          False                 False                   0.000114
                                   True                    0.001767
             True                  False                   0.000141
                                   True                    0.011356
nar-enc      False                 False                   0.000069
                                   True                    0.005423
             True                  False                   0.000099
                                   True                    0.005279

                                                          best_epoch  \
                                                                mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                   11.333333
                                   True                     1.000000
             True                  False                    6.000000
                                   True                     3.666667
ar-enc       False                 False                    8.333333
                                   True                     0.666667
             True                  False                    9.666667
                                   True                     0.000000
ffn          False                 False                   15.000000
                                   True                    14.666667
             True                  False                   15.000000
                                   True                    13.000000
nar          False                 False                   15.000000
                                   True                    15.000000
             True                  False                   15.000000
                                   True                    14.000000
nar-enc      False                 False                   15.000000
                                   True                    15.000000
             True                  False                   14.666667
                                   True                    14.333333

                                                                    best_step  \
                                                                std      mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                   4.618802   56499.0
                                   True                    1.732051    6999.0
             True                  False                   2.645751   31499.0
                                   True                    6.350853   18499.0
ar-enc       False                 False                   5.773503   41999.0
                                   True                    1.154701    4999.0
             True                  False                   6.806859   48499.0
                                   True                    0.000000    2499.0
ffn          False                 False                   0.000000   73999.0
                                   True                    0.577350   71999.0
             True                  False                   0.000000   74999.0
                                   True                    2.645751   62499.0
nar          False                 False                   0.000000   74499.0
                                   True                    0.000000   73999.0
             True                  False                   0.000000   72999.0
                                   True                    1.000000   68999.0
nar-enc      False                 False                   0.000000   74499.0
                                   True                    0.000000   72999.0
             True                  False                   0.577350   72999.0
                                   True                    0.577350   70499.0

                                                                         \
                                                                    std
decoder_type input_relative_coords output_relative_coords
ar           False                 False                   21702.534414
                                   True                     9526.279442
             True                  False                   11905.880900
                                   True                    29444.863729
ar-enc       False                 False                   28618.176043
                                   True                     6062.177826
             True                  False                   32668.792448
                                   True                     1732.050808
ffn          False                 False                     866.025404
                                   True                     2598.076211
             True                  False                       0.000000
                                   True                    13105.342422
nar          False                 False                     866.025404
                                   True                      866.025404
             True                  False                     866.025404
                                   True                     5408.326913
nar-enc      False                 False                     866.025404
                                   True                     1732.050808
             True                  False                    2291.287847
                                   True                     4500.000000

                                                          best_val_loss  \
                                                                   mean
decoder_type input_relative_coords output_relative_coords
ar           False                 False                       0.255153
                                   True                        0.039229
             True                  False                       0.514870
                                   True                        0.032946
ar-enc       False                 False                       0.211414
                                   True                        0.057565
             True                  False                       0.407591
                                   True                        0.037146
ffn          False                 False                       0.002958
                                   True                        0.004913
             True                  False                       0.004697
                                   True                        0.004529
nar          False                 False                       0.003060
                                   True                        0.004040
             True                  False                       0.004516
                                   True                        0.003281
nar-enc      False                 False                       0.002326
                                   True                        0.003672
             True                  False                       0.003740
                                   True                        0.003388


                                                                std
decoder_type input_relative_coords output_relative_coords
ar           False                 False                   0.029469
                                   True                    0.005272
             True                  False                   0.070068
                                   True                    0.003993
ar-enc       False                 False                   0.013302
                                   True                    0.026323
             True                  False                   0.039653
                                   True                    0.003607
ffn          False                 False                   0.000113
                                   True                    0.000155
             True                  False                   0.000177
                                   True                    0.000436
nar          False                 False                   0.000180
                                   True                    0.000122
             True                  False                   0.000116
                                   True                    0.000264
nar-enc      False                 False                   0.000083
                                   True                    0.000056
             True                  False                   0.000083
                                   True                    0.000074

In [10]:
results_df = {"best_epoch": [], "best_step": [], "best_val_loss": [], "relative_coords": [], "pen_state": [], "stroke_embedding": [], "sketch_pos": [], "stroke_pos": [], "test_p_metric": [], "test_c_metric": [], "seed": []}

for filename in os.listdir(f"../../sketch-segmentation/checkpoints/experiment3/"):
    if not os.path.exists(f"../../sketch-segmentation/results/experiment3/{filename}.pkl"):
        continue

    checkpoint_df = pd.read_csv(f"../../sketch-segmentation/checkpoints/experiment3/{filename}/lightning_logs/version_0/metrics.csv")
    metrics = checkpoint_df.iloc[checkpoint_df['val_loss'].idxmin()]
    results_df["best_epoch"].append(metrics['epoch'].astype(int))
    results_df["best_step"].append(metrics['step'].astype(int))
    results_df["best_val_loss"].append(metrics['val_loss'])

    with open(f"../../sketch-segmentation/results/experiment3/{filename}.pkl", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys() - {"dataset"}:
            if key in ["run", "best_epoch", "best_step", "best_val_loss"]: continue
            results_df[key].append(results["test_results"][key] if key in ["test_p_metric", "test_c_metric"] else results["args"][key])

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["relative_coords", "pen_state", "stroke_embedding", "sketch_pos", "stroke_pos"])[['test_p_metric', 'test_c_metric', 'best_epoch', 'best_step', 'best_val_loss']].agg(['mean', 'std'])
results_df[('test_p_metric', 'mean')] = results_df[('test_p_metric', 'mean')] * 100
results_df[('test_p_metric', 'mean')] = results_df[('test_p_metric', 'mean')].round(2)
results_df[('test_p_metric', 'std')] = results_df[('test_p_metric', 'std')] * 100
results_df[('test_p_metric', 'std')] = results_df[('test_p_metric', 'std')].round(2).map(lambda x: f"{x:05.2f}")
results_df[('test_p_metric', 'std')]
results_df

                                                                 test_p_metric  \
                                                                          mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False              64.53
                                                      True               78.45
                                           True       False              80.43
                          True             False      False              87.03
                                                      True               86.48
                                           True       False              84.61
                True      False            False      False              68.17
                                                      True               82.71
                                           True       False              87.19
True            False     False            False      False              18.61
                                                      True               40.60
                                           True       False              40.69
                          True             False      False              47.72
                                                      True               53.84
                                           True       False              49.20
                True      False            False      False              21.78
                                                      True               41.72
                                           True       False              48.05

                                                                         \
                                                                    std
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False       00.76
                                                      True        02.34
                                           True       False       02.75
                          True             False      False       01.43
                                                      True        01.75
                                           True       False       01.30
                True      False            False      False       01.50
                                                      True        00.47
                                           True       False       01.19
True            False     False            False      False       00.42
                                                      True        05.05
                                           True       False       00.72
                          True             False      False       02.62
                                                      True        00.54
                                           True       False       01.39
                True      False            False      False       01.10
                                                      True        02.14
                                           True       False       01.23

                                                                 test_c_metric  \
                                                                          mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False           0.468522
                                                      True            0.688138
                                           True       False           0.707582
                          True             False      False           0.812322
                                                      True            0.803329
                                           True       False           0.777950
                True      False            False      False           0.506983
                                                      True            0.744759
                                           True       False           0.802003
True            False     False            False      False           0.116722
                                                      True            0.286832
                                           True       False           0.313922
                          True             False      False           0.434118
                                                      True            0.481772
                                           True       False           0.438871
                True      False            False      False           0.129844
                                                      True            0.296851
                                           True       False           0.401667

                                                                            \
                                                                       std
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False       0.010585
                                                      True        0.026340
                                           True       False       0.032687
                          True             False      False       0.019489
                                                      True        0.023780
                                           True       False       0.018084
                True      False            False      False       0.020470
                                                      True        0.004713
                                           True       False       0.017726
True            False     False            False      False       0.008535
                                                      True        0.025498
                                           True       False       0.009258
                          True             False      False       0.026997
                                                      True        0.006949
                                           True       False       0.015673
                True      False            False      False       0.003115
                                                      True        0.012349
                                           True       False       0.009757

                                                                 best_epoch  \
                                                                       mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False            19.8
                                                      True             34.0
                                           True       False            24.4
                          True             False      False            27.2
                                                      True             18.6
                                           True       False            16.4
                True      False            False      False            18.2
                                                      True             45.6
                                           True       False            41.8
True            False     False            False      False             7.4
                                                      True             25.2
                                           True       False            17.2
                          True             False      False            20.0
                                                      True             20.6
                                           True       False            21.6
                True      False            False      False            20.2
                                                      True             26.0
                                           True       False            20.6

                                                                             \
                                                                        std
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False        2.683282
                                                      True        16.109004
                                           True       False       13.049904
                          True             False      False       10.639549
                                                      True         6.804410
                                           True       False        2.607681
                True      False            False      False        3.834058
                                                      True         8.648699
                                           True       False        4.919350
True            False     False            False      False        1.140175
                                                      True         3.271085
                                           True       False        1.303840
                          True             False      False        1.870829
                                                      True         2.607681
                                           True       False        1.516575
                True      False            False      False        8.105554
                                                      True         2.236068
                                           True       False        4.277850

                                                                 best_step  \
                                                                      mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False         1330.2
                                                      True          2239.0
                                           True       False         1624.6
                          True             False      False         1803.8
                                                      True          1253.4
                                           True       False         1112.6
                True      False            False      False         1227.8
                                                      True          2981.4
                                           True       False         2738.2
True            False     False            False      False          536.6
                                                      True          1675.8
                                           True       False         1163.8
                          True             False      False         1343.0
                                                      True          1381.4
                                           True       False         1445.4
                True      False            False      False         1355.8
                                                      True          1727.0
                                           True       False         1381.4

                                                                               \
                                                                          std
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False        171.730021
                                                      True        1030.976236
                                           True       False        835.193870
                          True             False      False        680.931127
                                                      True         435.482261
                                           True       False        166.891582
                True      False            False      False        245.379706
                                                      True         553.516757
                                           True       False        314.838371
True            False     False            False      False         72.971227
                                                      True         209.349469
                                           True       False         83.445791
                          True             False      False        119.733036
                                                      True         166.891582
                                           True       False         97.060806
                True      False            False      False        518.755434
                                                      True         143.108351
                                           True       False        273.782395

                                                                 best_val_loss  \
                                                                          mean
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False           1.218124
                                                      True            0.776473
                                           True       False           0.743838
                          True             False      False           0.541744
                                                      True            0.525952
                                           True       False           0.597320
                True      False            False      False           1.018923
                                                      True            0.650714
                                           True       False           0.557511
True            False     False            False      False           3.288916
                                                      True            2.170671
                                           True       False           2.380488
                          True             False      False           2.063567
                                                      True            1.858011
                                           True       False           2.015366
                True      False            False      False           3.076177
                                                      True            2.137204
                                           True       False           2.012444


                                                                       std
relative_coords pen_state stroke_embedding sketch_pos stroke_pos
False           False     False            False      False       0.061547
                                                      True        0.056900
                                           True       False       0.075213
                          True             False      False       0.038471
                                                      True        0.044671
                                           True       False       0.032709
                True      False            False      False       0.024315
                                                      True        0.048068
                                           True       False       0.045569
True            False     False            False      False       0.025271
                                                      True        0.214840
                                           True       False       0.035330
                          True             False      False       0.154664
                                                      True        0.054162
                                           True       False       0.053241
                True      False            False      False       0.066833
                                                      True        0.125929
                                           True       False       0.030333

In [13]:
results_df = {"best_epoch": [], "best_step": [], "best_val_loss": [], "relative_coords": [], "inter_stroke": [], "intra_stroke": [], "intra_stroke_rev": [], "stroke_order": [], "test_p_metric": [], "test_c_metric": [], "seed": []}

for filename in os.listdir(f"../../sketch-segmentation/checkpoints/experiment3_order/"):
    if not os.path.exists(f"../../sketch-segmentation/results/experiment3_order/{filename}.pkl"):
        continue

    checkpoint_df = pd.read_csv(f"../../sketch-segmentation/checkpoints/experiment3_order/{filename}/lightning_logs/version_0/metrics.csv")
    metrics = checkpoint_df.iloc[checkpoint_df['val_loss'].idxmin()]
    results_df["best_epoch"].append(metrics['epoch'].astype(int))
    results_df["best_step"].append(metrics['step'].astype(int))
    results_df["best_val_loss"].append(metrics['val_loss'])

    with open(f"../../sketch-segmentation/results/experiment3_order/{filename}.pkl", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys() - {"dataset"}:
            if key in ["run", "best_epoch", "best_step", "best_val_loss"]: continue
            results_df[key].append(results["test_results"][key] if key in ["test_p_metric", "test_c_metric"] else results["args"][key])

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["relative_coords", "inter_stroke", "intra_stroke", "intra_stroke_rev", "stroke_order"])[['test_p_metric', 'test_c_metric', 'best_epoch', 'best_step', 'best_val_loss']].agg(['mean', 'std'])
results_df[('test_p_metric', 'mean')] = results_df[('test_p_metric', 'mean')] * 100
results_df[('test_p_metric', 'mean')] = results_df[('test_p_metric', 'mean')].round(2)
results_df[('test_p_metric', 'std')] = results_df[('test_p_metric', 'std')] * 100
results_df[('test_p_metric', 'std')] = results_df[('test_p_metric', 'std')].round(2).map(lambda x: f"{x:05.2f}")
results_df[('test_p_metric', 'std')]
results_df

                                                                        test_p_metric  \
                                                                                 mean
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True                 82.81
                                          True             False                85.86
                                                           True                 83.18
                             True         False            False                86.20
                                                           True                 86.31
                True         False        False            False                65.36
True            False        False        False            True                 39.72
                                          True             False                46.76
                                                           True                 33.15
                             True         False            False                67.67
                                                           True                 63.06
                True         False        False            False                32.49

                                                                                \
                                                                           std
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True          01.56
                                          True             False         01.65
                                                           True          01.20
                             True         False            False         02.45
                                                           True          01.52
                True         False        False            False         00.36
True            False        False        False            True          03.49
                                          True             False         01.83
                                                           True          04.05
                             True         False            False         01.30
                                                           True          01.58
                True         False        False            False         00.75

                                                                        test_c_metric  \
                                                                                 mean
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True              0.730443
                                          True             False             0.782751
                                                           True              0.734626
                             True         False            False             0.791427
                                                           True              0.785076
                True         False        False            False             0.479289
True            False        False        False            True              0.345045
                                          True             False             0.414314
                                                           True              0.289906
                             True         False            False             0.589433
                                                           True              0.534420
                True         False        False            False             0.079552

                                                                                   \
                                                                              std
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True          0.018906
                                          True             False         0.022777
                                                           True          0.016813
                             True         False            False         0.035394
                                                           True          0.020491
                True         False        False            False         0.007740
True            False        False        False            True          0.027850
                                          True             False         0.018675
                                                           True          0.034348
                             True         False            False         0.014659
                                                           True          0.019307
                True         False        False            False         0.003548

                                                                        best_epoch  \
                                                                              mean
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True               52.4
                                          True             False              44.0
                                                           True               51.2
                             True         False            False              36.6
                                                           True               52.4
                True         False        False            False              20.2
True            False        False        False            True               21.0
                                          True             False              21.2
                                                           True               24.2
                             True         False            False              18.0
                                                           True               21.0
                True         False        False            False              16.6

                                                                                    \
                                                                               std
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True           3.911521
                                          True             False         15.165751
                                                           True           9.654015
                             True         False            False         17.444197
                                                           True           7.765307
                True         False        False            False          3.271085
True            False        False        False            True           2.345208
                                          True             False          2.489980
                                                           True           3.834058
                             True         False            False          2.449490
                                                           True           1.581139
                True         False        False            False          2.302173

                                                                        best_step  \
                                                                             mean
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True            3416.6
                                          True             False           2879.0
                                                           True            3339.8
                             True         False            False           2405.4
                                                           True            3416.6
                True         False        False            False           1355.8
True            False        False        False            True            1407.0
                                          True             False           1419.8
                                                           True            1611.8
                             True         False            False           1215.0
                                                           True            1407.0
                True         False        False            False           1125.4

                                                                                      \
                                                                                 std
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True           250.337372
                                          True             False          970.608057
                                                           True           617.856941
                             True         False            False         1116.428592
                                                           True           496.979678
                True         False        False            False          209.349469
True            False        False        False            True           150.093304
                                          True             False          159.358715
                                                           True           245.379706
                             True         False            False          156.767344
                                                           True           101.192885
                True         False        False            False          147.339065

                                                                        best_val_loss  \
                                                                                 mean
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True              0.681467
                                          True             False             0.587321
                                                           True              0.684357
                             True         False            False             0.569381
                                                           True              0.525989
                True         False        False            False             1.157098
True            False        False        False            True              2.274603
                                          True             False             2.143516
                                                           True              2.621258
                             True         False            False             1.226358
                                                           True              1.330237
                True         False        False            False             2.449416


                                                                              std
relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False           False        False        False            True          0.059199
                                          True             False         0.060062
                                                           True          0.034174
                             True         False            False         0.047326
                                                           True          0.026960
                True         False        False            False         0.061893
True            False        False        False            True          0.136617
                                          True             False         0.087555
                                                           True          0.135532
                             True         False            False         0.037562
                                                           True          0.043414
                True         False        False            False         0.033200

In [6]:
import yaml

results_df = {"input_relative_coords": [], "output_relative_coords": [], "test_l2_point": [], "seed": []}

for filename in os.listdir(f"../configs/decoder_studies/ffn/"):
    with open(f"../configs/decoder_studies/ffn/{filename}", "r") as file:
        config = yaml.safe_load(file)

    results_df['input_relative_coords'].append(config['pe']['input_relative_coords'])
    results_df['output_relative_coords'].append(config['pe']['output_relative_coords'])
    results_df['seed'].append(config['training']['seed'])

    with open(f"../{config['paths']['results']}", "rb") as file:
        results = pkl.load(file)


    results_df["test_l2_point"].append(results["test_results"]["test_l2_point"])

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["input_relative_coords", "output_relative_coords"])[['test_l2_point']].agg(['mean', 'std'])
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')] * 100
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')].round(3).map(lambda x: f"{x:06.3f}")
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')] * 100
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')].round(3).map(lambda x: f"{x:06.3f}")
results_df

                                             test_l2_point
                                                      mean     std
input_relative_coords output_relative_coords
False                 False                         00.261  00.005
                      True                          04.404  00.213
True                  False                         00.462  00.004
                      True                          10.423  02.512

In [4]:
import yaml
from pathlib import Path

results_df = {"input_relative_coords": [], "pen_state": [], "stroke_embedding": [], "stroke_pos": [], "sketch_pos": [], "test_l2_point": [], "seed": []}

for filename in os.listdir(f"../configs/pe/reconstruction/"):
    if filename == "base_config.yaml": continue
    with open(f"../configs/pe/reconstruction/{filename}", "r") as file:
        config = yaml.safe_load(file)
    results_path = Path("../").joinpath(config['paths']['results'])
    if not results_path.exists(): continue



    results_df['input_relative_coords'].append(config['pe']['input_relative_coords'])
    results_df['pen_state'].append(config['pe']['pen_state'])
    results_df['stroke_embedding'].append(config['pe']['stroke_embedding'])
    results_df['stroke_pos'].append(config['pe']['stroke_pos'])
    results_df['sketch_pos'].append(config['pe']['sketch_pos'])
    results_df['seed'].append(config['training']['seed'])
 
    with open(results_path, "rb") as file:
        results = pkl.load(file)


    results_df["test_l2_point"].append(results["test_results"]["test_l2_point"])

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["input_relative_coords", "pen_state", "stroke_embedding", "stroke_pos", "sketch_pos"])[['test_l2_point']].agg(['mean', 'std'])
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')] * 100
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')].round(3).map(lambda x: f"{x:06.3f}")
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')] * 100
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')].round(3).map(lambda x: f"{x:06.3f}")
results_df

                                                                       test_l2_point  \
                                                                                mean
input_relative_coords pen_state stroke_embedding stroke_pos sketch_pos
False                 False     False            False      False             34.609
                                                            True              00.303
                                                 True       False             18.471
                                True             False      False             20.123
                                                            True              00.316
                                                 True       False             00.377
                      True      False            False      False             33.047
                                                            True              00.222
                                                 True       False             16.299
True                  False     False            False      False             34.609
                                                            True              00.442
                                                 True       False             20.169
                                True             False      False             22.702
                                                            True              00.670
                                                 True       False             00.646
                      True      False            False      False             33.583
                                                 True       False             18.447


                                                                           std
input_relative_coords pen_state stroke_embedding stroke_pos sketch_pos
False                 False     False            False      False       00.000
                                                            True        00.008
                                                 True       False       00.011
                                True             False      False       00.000
                                                            True        00.006
                                                 True       False       00.009
                      True      False            False      False       00.001
                                                            True        000nan
                                                 True       False       00.008
True                  False     False            False      False       00.000
                                                            True        00.020
                                                 True       False       00.026
                                True             False      False       00.034
                                                            True        00.038
                                                 True       False       00.015
                      True      False            False      False       00.004
                                                 True       False       00.030

In [2]:
import yaml
from pathlib import Path

results_df = {"input_relative_coords": [],  "inter_stroke": [], "intra_stroke": [], "intra_stroke_rev": [], "stroke_order": [], "test_l2_point": [], "seed": []}

for filename in os.listdir(f"../configs/order/reconstruction/"):
    if filename == "base_config.yaml": continue
    with open(f"../configs/order/reconstruction/{filename}", "r") as file:
        config = yaml.safe_load(file)
    results_path = Path("../").joinpath(config['paths']['results'])
    if not results_path.exists(): continue



    results_df['input_relative_coords'].append(config['pe']['input_relative_coords'])
    results_df['inter_stroke'].append(config['perturbations']['inter_stroke'])
    results_df['intra_stroke'].append(config['perturbations']['intra_stroke'])
    results_df['intra_stroke_rev'].append(config['perturbations']['intra_stroke_rev'])
    results_df['stroke_order'].append(config['perturbations']['stroke_order'])
    results_df['seed'].append(config['training']['seed'])
 
    with open(results_path, "rb") as file:
        results = pkl.load(file)


    results_df["test_l2_point"].append(results["test_results"]["test_l2_point"])

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["input_relative_coords", "inter_stroke", "intra_stroke", "intra_stroke_rev", "stroke_order"])[['test_l2_point']].agg(['mean', 'std'])
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')] * 100
results_df[('test_l2_point', 'mean')] = results_df[('test_l2_point', 'mean')].round(3).map(lambda x: f"{x:06.3f}")
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')] * 100
results_df[('test_l2_point', 'std')] = results_df[('test_l2_point', 'std')].round(3).map(lambda x: f"{x:06.3f}")
results_df

                                                                              test_l2_point  \
                                                                                       mean
input_relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False                 False        False        False            True                00.228
                                                True             False               00.229
                                                                 True                00.232
                                   True         False            False               01.595
                                                                 True                01.857
                      True         False        False            False               03.699
True                  False        False        False            True                00.404
                                                True             False               00.393
                                                                 True                00.398
                                   True         False            False               02.030
                                                                 True                02.491
                      True         False        False            False               04.902


                                                                                  std
input_relative_coords inter_stroke intra_stroke intra_stroke_rev stroke_order
False                 False        False        False            True          00.006
                                                True             False         00.008
                                                                 True          00.009
                                   True         False            False         00.092
                                                                 True          00.084
                      True         False        False            False         00.286
True                  False        False        False            True          00.017
                                                True             False         00.015
                                                                 True          00.016
                                   True         False            False         00.092
                                                                 True          00.097
                      True         False        False            False         00.398