In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pickle as pkl

sns.set_style("darkgrid")

In [2]:
results_df = {"input_relative_coords": [], "output_relative_coords": [], "decoder_type": [], "test_acc": [], "seed": []}

for filename in os.listdir(f"../results/experiment4/"):

    with open(f"../results/experiment4/{filename}", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys():
            if key == "test_acc":
                value = results["test_results"][key]
            elif key not in results['pretraining_args'].keys():
                value = None
            else:
                value = results['pretraining_args'][key]
            
            results_df[key].append(value)

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["decoder_type", "input_relative_coords", "output_relative_coords"], dropna=False)[['test_acc']].agg(['mean', 'sem'])
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')] * 100
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')].round(2)
results_df[('test_acc', 'sem')] = results_df[('test_acc', 'sem')] * 100
results_df[('test_acc', 'sem')] = results_df[('test_acc', 'sem')].round(2).map(lambda x: f"{x:05.2f}")
results_df

                                                          test_acc
                                                              mean    sem
decoder_type input_relative_coords output_relative_coords
ffn          False                 False                     68.72  00.29
                                   True                      67.48  00.91
             True                  False                     68.76  00.31
                                   True                      57.62  01.66
nar          False                 False                     70.50  00.19
                                   True                      69.74  00.57
             True                  False                     69.24  00.28
                                   True                      66.73  00.31
nar-enc      False                 False                     69.45  00.28
                                   True                      68.86  00.74
             True                  False                     66.86  00.14
                                   True                      64.44  00.37
NaN          False                 NaN                       64.48  00.36
             True                  NaN                       64.36  00.41

In [3]:
results_df = {"input_relative_coords": [], "output_relative_coords": [], "decoder_type": [], "test_acc": [], "seed": []}

for filename in os.listdir(f"../results/experiment4b/"):

    with open(f"../results/experiment4b/{filename}", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys():
            if key == "test_acc":
                value = results["test_results"][key]
            elif key not in results['pretraining_args'].keys():
                value = None
            else:
                value = results['pretraining_args'][key]
            
            results_df[key].append(value)

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["decoder_type", "input_relative_coords", "output_relative_coords"], dropna=False)[['test_acc']].agg(['mean', 'sem'])
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')] * 100
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')].round(2)
results_df[('test_acc', 'sem')] = results_df[('test_acc', 'sem')] * 100
results_df[('test_acc', 'sem')] = results_df[('test_acc', 'sem')].round(2).map(lambda x: f"{x:05.2f}")
results_df

                                                          test_acc
                                                              mean    sem
decoder_type input_relative_coords output_relative_coords
ffn          False                 False                     51.27  00.32
                                   True                      49.09  00.15
             True                  False                     52.31  00.05
                                   True                      47.99  00.77
nar          False                 False                     58.48  00.11
                                   True                      54.61  00.67
             True                  False                     58.80  00.17
                                   True                      52.66  00.72
nar-enc      False                 False                     52.41  00.48
                                   True                      51.18  00.29
             True                  False                     52.18  00.16
                                   True                      49.29  00.05