In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pickle as pkl

sns.set_style("darkgrid")

In [3]:
results_df = {"input_relative_coords": [], "output_relative_coords": [], "decoder_type": [], "test_acc": [], "seed": []}

for filename in os.listdir(f"../../sketch-segmentation/results/experiment4/"):

    with open(f"../../sketch-segmentation/results/experiment4/{filename}", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys():
            if key == "test_acc":
                value = results["test_results"][key]
            elif key not in results['pretraining_args'].keys():
                value = None
            else:
                value = results['pretraining_args'][key]
            
            results_df[key].append(value)

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["decoder_type", "input_relative_coords", "output_relative_coords"], dropna=False)[['test_acc']].agg(['mean', 'std'])
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')] * 100
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')].round(2)
results_df[('test_acc', 'std')] = results_df[('test_acc', 'std')] * 100
results_df[('test_acc', 'std')] = results_df[('test_acc', 'std')].round(2).map(lambda x: f"{x:05.2f}")
results_df

                                                          test_acc
                                                              mean    std
decoder_type input_relative_coords output_relative_coords
ar           False                 False                     71.98  00.17
                                   True                      67.28  02.76
             True                  False                     71.70  00.68
                                   True                      66.49  03.67
ar-enc       False                 False                     71.38  00.87
                                   True                      66.15  03.48
             True                  False                     70.94  01.59
                                   True                      64.64  01.27
ffn          False                 False                     68.72  00.51
                                   True                      67.48  01.57
             True                  False                     68.76  00.54
                                   True                      57.62  02.87
nar          False                 False                     70.50  00.34
                                   True                      69.74  00.99
             True                  False                     69.24  00.49
                                   True                      66.73  00.53
nar-enc      False                 False                     69.45  00.48
                                   True                      68.86  01.28
             True                  False                     66.86  00.25
                                   True                      64.44  00.63
NaN          False                 NaN                       64.48  00.62
             True                  NaN                       64.36  00.70

In [4]:
results_df = {"input_relative_coords": [], "output_relative_coords": [], "decoder_type": [], "test_acc": [], "seed": []}

for filename in os.listdir(f"../../sketch-segmentation/results/experiment4b/"):

    with open(f"../../sketch-segmentation/results/experiment4b/{filename}", "rb") as file:
        results = pkl.load(file)

        for key in results_df.keys():
            if key == "test_acc":
                value = results["test_results"][key]
            elif key not in results['pretraining_args'].keys():
                value = None
            else:
                value = results['pretraining_args'][key]
            
            results_df[key].append(value)

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["decoder_type", "input_relative_coords", "output_relative_coords"], dropna=False)[['test_acc']].agg(['mean', 'std'])
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')] * 100
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')].round(2)
results_df[('test_acc', 'std')] = results_df[('test_acc', 'std')] * 100
results_df[('test_acc', 'std')] = results_df[('test_acc', 'std')].round(2).map(lambda x: f"{x:05.2f}")
results_df

                                                          test_acc
                                                              mean    std
decoder_type input_relative_coords output_relative_coords
ar           False                 False                     62.53  00.52
                                   True                      50.09  09.99
             True                  False                     62.27  00.24
                                   True                      37.58  20.34
ar-enc       False                 False                     59.94  00.31
                                   True                      49.27  09.27
             True                  False                     59.94  03.02
                                   True                      32.48  10.10
ffn          False                 False                     51.27  00.56
                                   True                      49.09  00.26
             True                  False                     52.31  00.09
                                   True                      47.99  01.34
nar          False                 False                     58.48  00.19
                                   True                      54.61  01.16
             True                  False                     58.80  00.29
                                   True                      52.66  01.24
nar-enc      False                 False                     52.41  00.83
                                   True                      51.18  00.51
             True                  False                     52.18  00.28
                                   True                      49.29  00.09

In [3]:
import yaml

results_df = {"input_relative_coords": [], "output_relative_coords": [], "test_acc": [], "seed": []}

for filename in os.listdir(f"../configs/transfer/ffn/"):
    with open(f"../configs/transfer/ffn/{filename}", "r") as file:
        config = yaml.safe_load(file)

    with open(f"../{config['paths']['model_config']}", "r") as file:
        model_config = yaml.safe_load(file)

    results_df['input_relative_coords'].append(model_config['pe']['input_relative_coords'])
    results_df['output_relative_coords'].append(model_config['pe']['output_relative_coords'])
    results_df['seed'].append(model_config['training']['seed'])

    with open(f"../{config['paths']['results']}", "rb") as file:
        results = pkl.load(file)


    results_df["test_acc"].append(results["test_results"]["test_acc"])

results_df = pd.DataFrame(results_df)
results_df = results_df.groupby(["input_relative_coords", "output_relative_coords"])[['test_acc']].agg(['mean', 'std'])
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')] * 100
results_df[('test_acc', 'mean')] = results_df[('test_acc', 'mean')].round(2).map(lambda x: f"{x:05.2f}")
results_df[('test_acc', 'std')] = results_df[('test_acc', 'std')] * 100
results_df[('test_acc', 'std')] = results_df[('test_acc', 'std')].round(2).map(lambda x: f"{x:05.2f}")
results_df

                                             test_acc
                                                 mean    std
input_relative_coords output_relative_coords
False                 False                     68.73  01.06
                      True                      67.96  00.93
True                  False                     68.23  00.28
                      True                      52.41  00.35